
"""
MIT License

Copyright (c) 2022-2025 Lawrence Byng

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""

""" debug level constants """
DEBUG_VERBOSE = 0
DEBUG_INFO    = 1
DEBUG_WARNING = 2
DEBUG_ERROR   = 3
DEBUG_OFF     = 4

DEBUG_OSMOD           = DEBUG_INFO
DEBUG_OSMOD_MOD       = DEBUG_INFO
DEBUG_OSMOD_DEMOD     = DEBUG_INFO
DEBUG_OSMOD_MAIN      = DEBUG_INFO

OSMOD_MODEM_8PSK      = 1
OSMOD_MODEM_8FSK      = 2
OSMOD_MODEM_OLIVIA    = 3
OSMOD_MODEM_APSK      = 4
OSMOD_MODEM_QPSK      = 5
OSMOD_MODEM_16QAM     = 6

EXTRACT_NORMAL    = 0
EXTRACT_INTERPOLATE   = 1

CHART_ONE           = 0
CHART_TWO           = 1
CHART_THREE         = 2
CHART_FOUR          = 3
CHART_ONE_A         = 4
CHART_TWO_A         = 5
CHART_THREE_A       = 6
CHART_FOUR_A        = 7

PHASE_ERROR_ACTUAL  = 0
PHASE_ERROR_ROUGH   = 1
PHASE_ERROR_SMOOTH  = 2


#"""csv_data = [mode, ebn0_db, SNR_equiv_db, ber, characters_per_second, bits_per_second, noise_factor, standingwave_pattern, standingwave_location] """

"""csv_data = [mode, ebn0_db, SNR_equiv_db, ber, characters_per_second, bits_per_second, noise_factor, standingwave_pattern, standingwave_location, preset_sw_pattern, chunk_size, rrc_alpha, rrc_t, extract_type, gaussian_sigma, detector_threshold_1, detector_threshold_2, basebandconv_freq_delta, costas_damping, costas_loop_bandwidth, costas_k1, costas_k2]"""

DATA_MODE                   = 0
DATA_EBN0_DB                = 1
DATA_SNR_EQUIV_DB           = 2
DATA_BER                    = 3
DATA_CPS                    = 4
DATA_BPS                    = 5
DATA_NOISE_FACTOR           = 6
DATA_SW_PATTERN_TYPE        = 7
DATA_SW_LOCATION            = 8
DATA_PRESET_PATTERN         = 9
DATA_CHUNK_SIZE             = 10
DATA_RRC_ALPHA              = 11
DATA_RRC_T                  = 12
DATA_EXTRACT_TYPE           = 13
DATA_PULSE_TRAIN_SIGMA      = 14
DATA_DETECTOR_THRESHOLD_1   = 15
DATA_DETECTOR_THRESHOLD_2   = 16
DATA_BASEBAND_FREQ_DELTA    = 17
DATA_COSTAS_DAMPING         = 18
DATA_COSTAS_LOOP_BANDWIDTH  = 19
DATA_COSTAS_K1              = 20
DATA_COSTAS_K2              = 21
DATA_ROTATION_LO            = 22
DATA_ROTATION_HI            = 23
DATA_PULSE_TRAIN_LENGTH     = 24
DATA_DISPOSITION            = 25
DATA_DOWNCONVERT_SHIFT      = 26
DATA_GENERATOR_POLYNOMIAL_1 = 27
DATA_GENERATOR_POLYNOMIAL_2 = 28
DATA_GENERATOR_POLY_DEPTH   = 29
DATA_CALC_1                 = 30
DATA_CALC_2                 = 31


""" used for intra block phase encoding """
PHASE_INTRA_SINGLE  = 0
PHASE_INTRA_TRIPLE  = 1

INTRA_EXTRACT_TYPE1  = 0
INTRA_EXTRACT_TYPE2  = 1
INTRA_EXTRACT_TYPE3  = 2
INTRA_EXTRACT_TYPE4  = 3
INTRA_EXTRACT_TYPE5  = 4
INTRA_EXTRACT_TYPE6  = 5
INTRA_EXTRACT_TYPE7  = 6

INTRA_COMBINE_TYPE1  = 0
INTRA_COMBINE_TYPE2  = 1
INTRA_COMBINE_TYPE3  = 2
INTRA_COMBINE_TYPE4  = 3
INTRA_COMBINE_TYPE5  = 4
INTRA_COMBINE_TYPE6  = 5
INTRA_COMBINE_TYPE7  = 6
INTRA_COMBINE_TYPE8  = 7
INTRA_COMBINE_TYPE9  = 8
INTRA_COMBINE_TYPE10 = 9

INTRA_COMPARE_TYPE1  = 0
INTRA_COMPARE_TYPE2  = 1
INTRA_COMPARE_TYPE3  = 2
INTRA_COMPARE_TYPE4  = 3
INTRA_COMPARE_TYPE5  = 4
INTRA_COMPARE_TYPE6  = 5

PULSE_A              = 0
PULSE_B              = 1
PULSE_C              = 2

OFFSETS_MANUAL       = 0
OFFSETS_PATTERN1     = 1
OFFSETS_PATTERN2     = 2
OFFSETS_PATTERN3     = 3
OFFSETS_PATTERN4     = 4
OFFSETS_PATTERN5     = 5
OFFSETS_PATTERN6     = 6
OFFSETS_PATTERN7     = 7
OFFSETS_PATTERN8     = 8
OFFSETS_PATTERN9     = 9
OFFSETS_PATTERN10    = 10
OFFSETS_PATTERN11    = 11
OFFSETS_PATTERN12    = 12
OFFSETS_PATTERN13    = 13
OFFSETS_PATTERN14    = 14
OFFSETS_PATTERN15    = 15
OFFSETS_PATTERN16    = 16
OFFSETS_PATTERN17    = 17
OFFSETS_PATTERN18    = 18
OFFSETS_PATTERN19    = 19
OFFSETS_PATTERN20    = 20
OFFSETS_PATTERN21    = 21
OFFSETS_PATTERN22    = 22
OFFSETS_PATTERN23    = 23
OFFSETS_PATTERN24    = 24
OFFSETS_PATTERN25    = 25
OFFSETS_PATTERN26    = 26
OFFSETS_PATTERN27    = 27
OFFSETS_PATTERN28    = 28
OFFSETS_PATTERN29    = 29
OFFSETS_PATTERN30    = 30
OFFSETS_PATTERN31    = 31
OFFSETS_PATTERN32    = 32
OFFSETS_PATTERN33    = 33
OFFSETS_PATTERN34    = 34
OFFSETS_PATTERN35    = 35
OFFSETS_PATTERN36    = 36
OFFSETS_PATTERN37    = 37
OFFSETS_PATTERN38    = 38
OFFSETS_PATTERN39    = 39
OFFSETS_PATTERN40    = 40
OFFSETS_PATTERN41    = 41
OFFSETS_PATTERN42    = 42
OFFSETS_PATTERN43    = 43
OFFSETS_PATTERN44    = 44
OFFSETS_PATTERN45    = 45
OFFSETS_PATTERN46    = 46
OFFSETS_PATTERN47    = 47
OFFSETS_PATTERN48    = 48
OFFSETS_PATTERN49    = 49
OFFSETS_PATTERN50    = 50

I3_STANDINGWAVE_PULSE_1_OF_3 = 0
I3_STANDINGWAVE_PULSE_2_OF_3 = 1
I3_STANDINGWAVE_PULSE_3_OF_3 = 2

PULSE_DETECTION_NORMAL = 0
PULSE_DETECTION_I3     = 1

ALIGN_RETAIN_LOCATION  = 0
ALIGN_MOVE_TO_MID      = 1

TRIPLETS_SUPERPOSITION = 0
TRIPLETS_SEQUENTIAL    = 1

DIFF_TREND_UP          = 0
DIFF_TREND_DOWN        = 1

LOCATE_PULSE_START_INDEX    = 0
LOCATE_PULSE_TRAIN          = 1
CALC_BLOCK_OFFSETS          = 2
CALC_PULSE_OFFSETS          = 3
LOCATE_PULSES_PEAK          = 4
PULSE_DETECT_INFO           = 5
CALC_BLOCK_OFFSETS_FRACTION = 6
FIND_TRIPLET_MAX_POINT      = 7

SIGNAL_ENVELOPE_GAUSSIAN       = 0
SIGNAL_ENVELOPE_HILBERT        = 1
SIGNAL_ENVELOPE_SAVITZKY_GOLAY = 2
SIGNAL_ENVELOPE_HILBERT_GAUSS  = 3
SIGNAL_ENVELOPE_HILBERT_SG     = 4

PULSE_SHAPE_MANUAL              = 0
PULSE_SHAPE_MODULATION_SPECIFIC = 1
PULSE_SHAPE_GENERAL             = 2
PULSE_SHAPE_TEST                = 3

PARAM_EXTRACT_THRESHOLD         = 0
PARAM_RRC_ALPHA                 = 1
PARAM_RRC_T                     = 2
PARAM_BASEBAND_NORMALIZATION    = 3
PARAM_EXTRACT_NUM_WAVES         = 4
PARAM_AT_MAX_PERCENT            = 5
PARAM_COSTAS_LOOP_DAMPING       = 6
PARAM_COSTAS_LOOP_BANDWIDTH     = 7
PARAM_COSTAS_LOOP_K1            = 8
PARAM_COSTAS_LOOP_K2            = 9

EXTRAPOLATE_NONE                       = 0
EXTRAPOLATE_FIND_DISPOSITION_ROTATION  = 1
EXTRAPOLATE_FIXED_ROTATION_DECODE      = 2

DISPOSITION_NO_MATCH            = 0
DISPOSITION_MATCH_SINGLE        = 1
DISPOSITION_MATCH_AMBIGUOUS     = 2

FEC_NONE                        = 0
FEC_VITERBI                     = 1
FEC_VITERBI2                    = 2
FEC_LDPC                        = 3
FEC_TURBO                       = 4

MSGTYPE_FIXED_LENGTH            = 0
MSGTYPE_VARIABLE_LENGTH         = 1

HOLOGRAPH_DECODE_NONE           = 0
HOLOGRAPH_DECODE_ThREE          = 1
HOLOGRAPH_DECODE_FIVE           = 2
HOLOGRAPH_DECODE_SEVEN          = 3



